name: Docker Image CI

on:
  push:
    branches:
    - master
    - renovate/*
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag renovate/base
    - name: Image history
      run: docker history renovate/base
